runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: app/dist/static
- url: /.*
  script: main.app

libraries:
- name: numpy
  version: "1.6.1"

skip_files:
# default
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# end of default
- ^app/node_modules$
- ^(.*/)?\.vue$
- ^(.*/)?\LICENSE$
- ^(.*/)?\package.json$
- ^(.*/)?\README.md$
- ^(.*/)?\webpack.config.js$
